on:
  pull_request:
  push:
    branches:
      - master
      - ci
jobs:
  release:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build example --verbose
      - name: "Fetch tags"
        id: fetch-tags
        uses: actions/github-script@v2
        with:
          script: |
            return require(`${process.env.GITHUB_WORKSPACE}/package.json`).version
          result-encoding: string

      - name: Upload release binaries
        uses: boxpositron/upload-multiple-releases@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          release_config: |
            zig-out/cmake/*
          tag_name: v${{ steps.fetch-tags.outputs.result }}
          release_name: ${{ steps.fetch-tags.outputs.result }}
          draft: false
          prerelease: false
          overwrite: true
